// i18n / locale-pack emission. Emits public/locales/<locale>/common.json for
// each requested locale, plus a minimal src/i18n.ts i18next bootstrap. RTL
// locales (ar, he, fa, ur) trigger a global CSS rule targeting html[dir="rtl"].

import fs from 'node:fs/promises'
import { dirname, join } from 'node:path'

import { ensureDir } from '../fs.js'

import type { BrandKit } from './index.js'

export const RTL_LOCALES = new Set(['ar', 'he', 'fa', 'ur'])

export type LocalePack = Record<string, string>

export function isRtl(locale: string): boolean {
  return RTL_LOCALES.has(locale.split('-')[0].toLowerCase())
}

// Minimal translation table per locale — the hero strings are brand-specific
// (substituted from the kit); common UI strings are hand-translated for the
// small baseline set. Real products extend via their own translation flow.
const COMMON_STRINGS: Record<string, Record<string, string>> = {
  en: {
    get_started: 'Get started',
    learn_more: 'Learn more',
    sign_in: 'Sign in',
    sign_out: 'Sign out',
  },
  es: {
    get_started: 'Comenzar',
    learn_more: 'Saber más',
    sign_in: 'Iniciar sesión',
    sign_out: 'Cerrar sesión',
  },
  fr: {
    get_started: 'Commencer',
    learn_more: 'En savoir plus',
    sign_in: 'Se connecter',
    sign_out: 'Se déconnecter',
  },
  de: {
    get_started: 'Loslegen',
    learn_more: 'Mehr erfahren',
    sign_in: 'Anmelden',
    sign_out: 'Abmelden',
  },
  ja: {
    get_started: 'はじめる',
    learn_more: '詳細を見る',
    sign_in: 'サインイン',
    sign_out: 'サインアウト',
  },
  ar: {
    get_started: 'ابدأ',
    learn_more: 'اعرف المزيد',
    sign_in: 'تسجيل الدخول',
    sign_out: 'تسجيل الخروج',
  },
  he: { get_started: 'התחל', learn_more: 'למידע נוסף', sign_in: 'כניסה', sign_out: 'יציאה' },
  pt: { get_started: 'Começar', learn_more: 'Saiba mais', sign_in: 'Entrar', sign_out: 'Sair' },
  zh: { get_started: '开始', learn_more: '了解更多', sign_in: '登录', sign_out: '登出' },
}

export function generateLocalePack(kit: BrandKit, locale: string): LocalePack {
  const base = COMMON_STRINGS[locale] ?? COMMON_STRINGS.en
  return {
    ...base,
    brand_name: kit.brandName,
    brand_tagline: kit.tagline,
    hero_headline: kit.heroHeadline,
    hero_subheadline: kit.heroSubheadline,
  }
}

export interface I18nEmitResult {
  locales: string[]
  files: { path: string; body: string }[]
  rtlEnabled: boolean
}

export function buildI18nFiles(kit: BrandKit, locales: string[]): I18nEmitResult {
  const files: { path: string; body: string }[] = []
  const rtlEnabled = locales.some((l) => isRtl(l))

  for (const locale of locales) {
    const pack = generateLocalePack(kit, locale)
    files.push({
      path: `public/locales/${locale}/common.json`,
      body: JSON.stringify(pack, null, 2) + '\n',
    })
  }

  // Minimal i18next bootstrap for consumers that want it. Keeps the runtime
  // optional — the composed scaffold can import it or skip it.
  const bootstrap = `// Auto-generated by starter-foundry. Minimal i18next setup.
// Extend or replace freely — the locale packs in public/locales/ are the source of truth.
import i18next from 'i18next'

const locales = ${JSON.stringify(locales)}
const defaultLocale = ${JSON.stringify(locales[0] ?? 'en')}

export async function initI18n(): Promise<typeof i18next> {
  const resources: Record<string, { translation: Record<string, string> }> = {}
  for (const locale of locales) {
    const pack = await fetch(\`/locales/\${locale}/common.json\`).then((r) => r.json())
    resources[locale] = { translation: pack }
  }
  await i18next.init({
    lng: defaultLocale,
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
    resources,
  })
  return i18next
}

export function setLocale(locale: string): void {
  void i18next.changeLanguage(locale)
  if (typeof document !== 'undefined') {
    const rtl = ${JSON.stringify([...RTL_LOCALES])}
    document.documentElement.dir = rtl.includes(locale.split('-')[0]) ? 'rtl' : 'ltr'
    document.documentElement.lang = locale
  }
}
`
  files.push({ path: 'src/i18n.ts', body: bootstrap })

  if (rtlEnabled) {
    const rtlCss = `/* RTL direction flip — applied when the active locale is in ${[...RTL_LOCALES].join(', ')}. */
html[dir="rtl"] {
  direction: rtl;
  text-align: right;
}
html[dir="rtl"] .reverse-on-rtl { flex-direction: row-reverse; }
`
    files.push({ path: 'public/rtl.css', body: rtlCss })
  }

  return { locales, files, rtlEnabled }
}

export async function emitI18n(
  kit: BrandKit,
  outDir: string,
  locales: string[],
): Promise<I18nEmitResult> {
  const result = buildI18nFiles(kit, locales)
  for (const f of result.files) {
    const abs = join(outDir, f.path)
    await ensureDir(dirname(abs))
    await fs.writeFile(abs, f.body, 'utf8')
  }
  return result
}
