// Two protocol responsibilities in one file:
//
//   1. `app://` — a bundled-asset protocol for loading the renderer in
//      production without exposing the file:// surface. Must be declared
//      as "privileged" (secure, supports fetch) BEFORE app.whenReady(),
//      then registered as a file handler AFTER whenReady.
//
//   2. `{{packageName}}://` — the OS-wide deep-link scheme. Registration
//      is handled by electron-builder's `protocols` block for installed
//      builds and by app.setAsDefaultProtocolClient for dev.

import { app, protocol, net } from "electron";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEEP_LINK_SCHEME = "{{packageName}}";

export function registerPrivilegedSchemes(): void {
  protocol.registerSchemesAsPrivileged([
    {
      scheme: "app",
      privileges: {
        standard: true,
        secure: true,
        supportFetchAPI: true,
        corsEnabled: true,
      },
    },
  ]);

  // Deep-link registration. On macOS this is declarative via Info.plist
  // (generated by electron-builder's protocols block). On Windows/Linux
  // we still call setAsDefaultProtocolClient for dev-mode runs.
  if (process.defaultApp) {
    if (process.argv.length >= 2) {
      app.setAsDefaultProtocolClient(DEEP_LINK_SCHEME, process.execPath, [
        path.resolve(process.argv[1]!),
      ]);
    }
  } else {
    app.setAsDefaultProtocolClient(DEEP_LINK_SCHEME);
  }
}

export function registerAppProtocol(): void {
  // Electron 25+ prefers protocol.handle over registerFileProtocol.
  protocol.handle("app", async (request) => {
    const url = new URL(request.url);
    // "app://local/index.html" -> resolve against the packaged renderer.
    const rendererRoot = path.join(__dirname, "../renderer");
    const filePath = path.join(rendererRoot, url.pathname);
    return net.fetch(pathToFileURL(filePath).toString());
  });
}
