[package]
name = "script"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "prove"
path = "src/main.rs"

[dependencies]
sp1-sdk = "4.0"
serde = { version = "1", features = ["derive"] }
anyhow = "1"

[build-dependencies]
sp1-build = "4.0"
