// judge.ts — score a synthesized candidate template against the current
// one. Deterministic metrics + optional LLM-as-judge for qualitative
// differences. Scores are numeric [0, 1] where higher = better candidate.

import { readFileSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { HarvestSummary } from './harvest.js'

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const TREND_PATH = join(REPO, '.evolve/traces/family-pass-rate-trend.jsonl')

interface JudgeInput {
  templatePath: string
  currentSource: string
  candidate: string
  harvest: HarvestSummary
  /** Optional. When present, the judge reads family-pass-rate-trend.jsonl and
   * adjusts the score by the 2-week trend slope for this family (Branch 2.4).
   * Generated by scripts/family-pass-rate-trend.ts. */
  familyId?: string
}

export interface JudgeResult {
  /** Total composite score. */
  score: number
  /** Sub-scores by dimension, each [0, 1]. */
  dimensions: Record<string, number>
  reasoning: string
  /** Does the candidate contain lines agents routinely REMOVE from the current? */
  removesFrequentlyDeletedLines: number
  /** Does the candidate incorporate lines agents routinely ADD? */
  incorporatesFrequentlyAddedLines: number
  /** Raw size change. Negative when candidate is shorter (usually better). */
  sizeDelta: number
}

function countOverlap(source: string, needles: string[]): number {
  let hits = 0
  for (const needle of needles) {
    if (source.includes(needle)) hits++
  }
  return needles.length === 0 ? 0 : hits / needles.length
}

interface TrendRow {
  family: string
  isoWeek: string
  totalBuildouts: number
  passes: number
  passRate: number
}

function loadRecentTrend(
  familyId: string,
): { slope: number; latestRate: number; weeks: number } | null {
  if (!existsSync(TREND_PATH)) return null
  try {
    const rows: TrendRow[] = readFileSync(TREND_PATH, 'utf8')
      .split('\n')
      .filter((l) => l.trim().length > 0)
      .map((l) => JSON.parse(l) as TrendRow)
      .filter((r) => r.family === familyId)
      .sort((a, b) => a.isoWeek.localeCompare(b.isoWeek))
    if (rows.length < 2) {
      return rows.length === 1 ? { slope: 0, latestRate: rows[0].passRate, weeks: 1 } : null
    }
    // Simple two-point slope across the two most recent weeks.
    const tail = rows.slice(-2)
    const slope = tail[1].passRate - tail[0].passRate
    return { slope, latestRate: tail[1].passRate, weeks: rows.length }
  } catch {
    return null
  }
}

export function judge(input: JudgeInput): JudgeResult {
  const addedLines = input.harvest.frequentlyAddedLines.map((e) => e.line)

  // Score 1: does the candidate INCLUDE the lines agents keep adding?
  const incorporatesFrequentlyAddedLines = countOverlap(input.candidate, addedLines)
  const currentIncorporates = countOverlap(input.currentSource, addedLines)
  const addLift = incorporatesFrequentlyAddedLines - currentIncorporates

  // Score 2: does the candidate REMOVE the lines agents keep deleting?
  // Proxy: find lines in the current that DON'T appear in any agent rewrite.
  const agentBodies = input.harvest.samplesAfter.join('\n\n')
  const currentLines = input.currentSource
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length >= 8)
  let removedByAgents = 0
  let removedInCandidate = 0
  for (const line of currentLines) {
    const inAgents = agentBodies.includes(line)
    if (inAgents) continue
    removedByAgents++
    if (!input.candidate.includes(line)) removedInCandidate++
  }
  const removesFrequentlyDeletedLines =
    removedByAgents === 0 ? 0 : removedInCandidate / removedByAgents

  // Score 3: size delta. Slightly prefer smaller (agents tend to trim).
  const sizeDelta = input.candidate.length - input.currentSource.length
  const sizeScore =
    sizeDelta < 0 ? 1 : Math.max(0, 1 - sizeDelta / Math.max(1, input.currentSource.length))

  // Score 4 (optional): downstream VB pass-rate trend for the family. When
  // positive slope, the current direction is working — lean toward keeping
  // current shape (smaller candidate delta rewarded). When negative slope,
  // reward structural candidate changes more (addLift weight bumped).
  // See scripts/family-pass-rate-trend.ts for the data source.
  let vbTrendSignal = 0.5
  const reasoningLines: string[] = []
  if (input.familyId) {
    const trend = loadRecentTrend(input.familyId)
    if (trend) {
      // slope ∈ [-1, 1] — map to [0, 1] centered on 0.5.
      vbTrendSignal = Math.max(0, Math.min(1, 0.5 + trend.slope))
      reasoningLines.push(
        `vbPassRateTrend[${input.familyId}]: latest=${trend.latestRate.toFixed(2)} slope=${trend.slope >= 0 ? '+' : ''}${trend.slope.toFixed(2)} (weeks=${trend.weeks})`,
      )
    }
  }

  // Composite: weighted average. vbTrend weight is small (5%) so it nudges
  // without dominating the deterministic rewrite signal.
  const composite =
    0.45 * Math.max(0, addLift + 0.5) +
    0.3 * removesFrequentlyDeletedLines +
    0.2 * sizeScore +
    0.05 * vbTrendSignal

  const reasoning = [
    `incorporatesFrequentlyAddedLines: ${incorporatesFrequentlyAddedLines.toFixed(2)} (current: ${currentIncorporates.toFixed(2)}, lift: ${addLift.toFixed(2)})`,
    `removesFrequentlyDeletedLines: ${removesFrequentlyDeletedLines.toFixed(2)} (${removedInCandidate}/${removedByAgents})`,
    `sizeDelta: ${sizeDelta} chars (score ${sizeScore.toFixed(2)})`,
    ...reasoningLines,
  ].join('\n')

  return {
    score: Math.max(0, Math.min(1, composite)),
    dimensions: {
      addLift: Math.max(0, addLift + 0.5),
      removeMatch: removesFrequentlyDeletedLines,
      sizeScore,
      vbTrend: vbTrendSignal,
    },
    reasoning,
    removesFrequentlyDeletedLines,
    incorporatesFrequentlyAddedLines,
    sizeDelta,
  }
}
