// Ambient type stub for wasm-pack output. The real module is generated by
// `pnpm run build:wasm` (via wasm-bindgen). This stub lets `tsc --noEmit`
// succeed before the wasm has been built. Keep the signatures in sync with
// the #[wasm_bindgen] exports in src/lib.rs.
export default function init(input?: unknown): Promise<unknown>
export function greet(name: string): string
export function fibonacci(n: number): number
