[package]
name = "host"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
risc0-zkvm = { workspace = true }
methods = { path = "../methods" }
serde = { workspace = true }
bincode = { workspace = true }
anyhow = "1"
