#!/usr/bin/env node
// One-shot bring-up for a local cli-bridge that starter-foundry's
// self-heal loop and pr-reviewer's DSPy-RLM path can both target via
// tcloud BYOB headers.
//
// What it does:
//   1. Verifies cli-bridge checkout exists at $CLI_BRIDGE_DIR
//      (default ~/code/cli-bridge)
//   2. Probes for the harness binaries (claude, kimi, codex, opencode);
//      reports which subscriptions/auth still need `<bin> login`
//   3. Generates a fresh BRIDGE_BEARER, writes it + harness env to
//      $CLI_BRIDGE_DIR/.env.local
//   4. Prints the exact commands to:
//        - start the local server (`pnpm exec tsx src/server.ts`)
//        - export CLI_BRIDGE_URL + CLI_BRIDGE_BEARER for starter-foundry
//        - hit the health endpoint to verify
//
// Doesn't actually start the server — that's a foreground process; you
// want to manage it (tmux pane, dedicated terminal, systemd, etc.).

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'
import { spawnSync, execSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'

const CLI_BRIDGE_DIR = process.env['CLI_BRIDGE_DIR'] ?? join(homedir(), 'code', 'cli-bridge')

if (!existsSync(join(CLI_BRIDGE_DIR, 'package.json'))) {
  process.stderr.write(
    `[setup] cli-bridge checkout not found at ${CLI_BRIDGE_DIR}\n` +
    `        Set CLI_BRIDGE_DIR to your local clone path, or:\n` +
    `        gh repo clone drewstone/cli-bridge ${CLI_BRIDGE_DIR}\n`
  )
  process.exit(1)
}

console.log(`[setup] cli-bridge: ${CLI_BRIDGE_DIR}`)

const HARNESSES = [
  { bin: 'claude', label: 'Claude Code',  unlock: 'claude /login (already done if `claude` runs)', usedFor: 'claude-code/* harness' },
  { bin: 'kimi',   label: 'Kimi Code',    unlock: 'kimi login',                                    usedFor: 'kimi-code/* harness' },
  { bin: 'codex',  label: 'Codex',        unlock: 'codex login',                                   usedFor: 'codex/* harness' },
  { bin: 'opencode', label: 'opencode',   unlock: 'opencode auth login',                           usedFor: 'opencode/* harness' },
]

const ready = []
const missing = []
for (const h of HARNESSES) {
  const probe = spawnSync(h.bin, ['--version'], { stdio: ['ignore', 'pipe', 'pipe'] })
  if (probe.status === 0) ready.push(h)
  else missing.push(h)
}
console.log(`[setup] harnesses on PATH: ${ready.map((h) => h.bin).join(', ') || '(none)'}`)
if (missing.length > 0) {
  console.log(`[setup] missing harnesses: ${missing.map((h) => h.bin).join(', ')} — those *-code routes will 503 until installed`)
}

const envPath = join(CLI_BRIDGE_DIR, '.env.local')
let bearer = ''
if (existsSync(envPath)) {
  const cur = readFileSync(envPath, 'utf8')
  const m = cur.match(/^BRIDGE_BEARER=(.+)$/m)
  bearer = m ? m[1].trim() : ''
}
if (!bearer) {
  bearer = `local-dev-${randomBytes(16).toString('hex')}`
}

const lines = [
  '# Generated by scripts/setup-local-cli-bridge.ts — safe to edit.',
  'BRIDGE_PORT=3344',
  'BRIDGE_HOST=127.0.0.1',
  `BRIDGE_BACKENDS=${ready.map((h) => h.bin === 'claude' ? 'claude' : h.bin).join(',') || 'passthrough'},passthrough`,
  `BRIDGE_BEARER=${bearer}`,
]
writeFileSync(envPath, lines.join('\n') + '\n')
console.log(`[setup] wrote ${envPath}`)

console.log()
console.log('=== next steps ===')
console.log()
console.log('1. Start the server (foreground, in its own terminal/tmux):')
console.log(`     cd ${CLI_BRIDGE_DIR} && export $(grep -v '^#' .env.local | xargs) && pnpm exec tsx src/server.ts`)
console.log()
console.log('2. Verify health (in a second terminal):')
console.log(`     curl -sS http://127.0.0.1:3344/health | python3 -m json.tool`)
console.log()
console.log('3. Export env in your starter-foundry shell — the SDK auto-picks the path:')
console.log()
console.log('   PATH 1 — direct local (cleanest, no router, no tunnel):')
console.log(`     export CLI_BRIDGE_URL=http://127.0.0.1:3344`)
console.log(`     export CLI_BRIDGE_BEARER='${bearer}'`)
console.log(`     # (do NOT set TCLOUD_API_KEY / BRIDGE_UNLOCK — they trigger router mode)`)
console.log()
console.log('   PATH 2 — BYOB via router (needs public tunnel + router gate creds):')
console.log(`     ngrok http 3344   # in another terminal — copy the https URL`)
console.log(`     export CLI_BRIDGE_URL=https://your-ngrok.ngrok.io`)
console.log(`     export CLI_BRIDGE_BEARER='${bearer}'`)
console.log(`     export TCLOUD_API_KEY=sk-tan-...`)
console.log(`     export BRIDGE_UNLOCK=...`)
console.log()
if (missing.length > 0) {
  console.log('4. Auth the missing harnesses (interactive — opens browser device-flow):')
  for (const h of missing) console.log(`     ${h.unlock.padEnd(35)}  # for ${h.usedFor}`)
  console.log()
}
console.log('Wire form: <harness>/<model>  (direct mode — no bridge/ prefix needed;')
console.log('cli-bridge accepts the harness id as the first path segment).')
console.log('  e.g. claude-code/sonnet, kimi-code/kimi-for-coding')
