// ZK proof helper — client-side Groth16 proof generation via snarkjs.
//
// Host the circuit's wasm + zkey under public/proving-keys/ and call
// generateProof with the public URLs. The returned proof is ready to submit
// to your verifier (on-chain Solidity verifier generated by snarkjs, or any
// Groth16-compatible verifier).

// snarkjs is published as an untyped CJS module — declare a minimal surface
// here so downstream TS code gets type safety on the calls we actually use.
declare module 'snarkjs' {
  export const groth16: {
    fullProve(
      input: Record<string, string | number | bigint | string[]>,
      wasmUrl: string,
      zkeyUrl: string,
    ): Promise<{ proof: Groth16Proof; publicSignals: string[] }>
    verify(
      verificationKey: unknown,
      publicSignals: string[],
      proof: Groth16Proof,
    ): Promise<boolean>
  }
}

export interface Groth16Proof {
  pi_a: [string, string, string]
  pi_b: [[string, string], [string, string], [string, string]]
  pi_c: [string, string, string]
  protocol: 'groth16'
  curve: string
}

export interface GeneratedProof {
  proof: Groth16Proof
  publicSignals: string[]
  /** Solidity-ABI-encoded calldata for the on-chain verifier contract. */
  solidityCalldata: string
}

/**
 * Generate a Groth16 proof in the browser.
 *
 * @param inputs - Circuit inputs keyed by signal name. Large numbers must be
 *   passed as strings or bigints; snarkjs rejects plain number >2^53.
 * @param wasmUrl - Public URL to the compiled circuit wasm.
 * @param zkeyUrl - Public URL to the proving key (.zkey).
 */
export async function generateProof(
  inputs: Record<string, string | number | bigint | string[]>,
  wasmUrl: string,
  zkeyUrl: string,
): Promise<GeneratedProof> {
  const { groth16 } = await import('snarkjs')
  const { proof, publicSignals } = await groth16.fullProve(inputs, wasmUrl, zkeyUrl)
  const solidityCalldata = buildSolidityCalldata(proof, publicSignals)
  return { proof, publicSignals, solidityCalldata }
}

/**
 * Verify a Groth16 proof client-side. Useful for "verify your note" UX —
 * confirm a downloadable proof is well-formed before the user submits it
 * on-chain.
 */
export async function verifyProof(
  verificationKey: unknown,
  publicSignals: string[],
  proof: Groth16Proof,
): Promise<boolean> {
  const { groth16 } = await import('snarkjs')
  return groth16.verify(verificationKey, publicSignals, proof)
}

/**
 * Poseidon hash via circomlibjs. Use for merkle tree commitments — most
 * circom circuits use Poseidon because it's ZK-friendly (cheap in
 * constraints).
 */
export async function poseidonHash(inputs: bigint[]): Promise<bigint> {
  const { buildPoseidon } = await import('circomlibjs')
  const poseidon = await buildPoseidon()
  const hash = poseidon(inputs)
  return BigInt(poseidon.F.toString(hash))
}

function buildSolidityCalldata(proof: Groth16Proof, publicSignals: string[]): string {
  // Encodes a snarkjs Groth16 proof in the shape the snarkjs-generated
  // Verifier.sol expects: [a, b, c, input]. Inline here so callers don't
  // need a second snarkjs import chain for pure-formatting work.
  const pA = `[${proof.pi_a[0]}, ${proof.pi_a[1]}]`
  const pB = `[[${proof.pi_b[0][1]}, ${proof.pi_b[0][0]}], [${proof.pi_b[1][1]}, ${proof.pi_b[1][0]}]]`
  const pC = `[${proof.pi_c[0]}, ${proof.pi_c[1]}]`
  const inputs = `[${publicSignals.join(', ')}]`
  return `${pA}, ${pB}, ${pC}, ${inputs}`
}
